pmpl/config/routes.rb
Oilcontrol::Application.routes.draw do
  
  resources :machine_historics

  get 'brands/import' => 'brands#import'
  post 'brands/import' => 'brands#upload'
  
  get 'carmodels/import' => 'carmodels#import'
  post 'carmodels/import' => 'carmodels#upload'
  
  get 'oils/import' => 'oils#import'
  post 'oils/import' => 'oils#upload'
  
  get 'places/import' => 'places#import'
  post 'places/import' => 'places#upload'
  
  get 'vehicles/import' => 'vehicles#import'
  post 'vehicles/import' => 'vehicles#upload'
  
  resources :report_vehicle_historics

  resources :places

  resources :carmodels

  resources :brands

  resources :vehicle_dailies

  get "user_sessions/new"

  resources :oils

  resources :vehicle_historics

  resources :vehicles
  
  resources :users
  
  resources :user_sessions
  
  match 'vehicle_historics/exchange/:id' => 'vehicle_historics#exchange', :as => :vehicle_historic_exchange
  match 'machine_historics/exchange/:id' => 'machine_historics#exchange', :as => :machine_historic_exchange
  
  match 'vehicles/update_carmodels_select/:id' => 'vehicles#update_carmodels_select'
  
  match 'vehicle_historics/update_oil_select/:id' => 'vehicle_historics#update_oil_select'
  match 'machine_historics/update_oil_select/:id' => 'machine_historics#update_oil_select'

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "vehicles#index"

end

pmpl/app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :vehicles, :dependent => :destroy
  has_many :carmodels, :dependent => :destroy
  
  validates :name, :presence => true
end

pmpl/app/models/carmodel.rb
class Carmodel < ActiveRecord::Base
  belongs_to :brand
  
  has_many :vehicles, :dependent => :destroy
  has_many :carmodel_oils, :dependent => :delete_all
  has_many :oils, :through => :carmodel_oils
  
  validates :brand_id, :name, :carmodel_type, :presence => true
  
  accepts_nested_attributes_for :carmodel_oils, :reject_if => lambda { |a| a[:km].blank? and a[:hour].blank? }, :allow_destroy => true

  Type = ["Caminhão", "Maquina"]
end

pmpl/app/models/carmodel_oil.rb
class CarmodelOil < ActiveRecord::Base
  belongs_to :carmodel
  belongs_to :oil
end

pmpl/app/models/data_file.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    upload_filename =  upload.original_filename
    
    extension = File.extname(upload_filename).gsub(/^\.+/, '')
    name = upload_filename.gsub(/\.#{extension}$/, '')
    
    # Downcase string
    name.downcase!
    # Remove apostrophes so isn't changes to isnt
    name.gsub!(/'/, '')
    # Replace any non-letter or non-number character with a space
    name.gsub!(/[^A-Za-z0-9]+/, ' ')
    # Remove spaces from beginning and end of string
    name.strip!
    # Replace groups of spaces with single hyphen
    name.gsub!(/\ +/, '-')
    
    filename = name + "." + extension

    directory = "public/data"
    # create the file path
    path = File.join(directory, filename)
    # write the file
    File.open(path, "wb") { |f| f.write(upload.read) }
    
    return filename 
  end
end

pmpl/app/models/machine_historic.rb
class MachineHistoric < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :oil
  has_many :vehicle_dailies
  
  validates :status, :vehicle_id, :oil_id, :presence => true
end

pmpl/app/models/oil.rb
class Oil < ActiveRecord::Base
  has_many :vehicle_historics, :dependent => :destroy
  has_many :carmodel_oils, :dependent => :destroy
  has_many :carmodels, :through => :carmodel_oils
    
  accepts_nested_attributes_for :carmodel_oils
  
  validates :name, :presence => true
end

pmpl/app/models/place.rb
class Place < ActiveRecord::Base
  has_many :vehicles
end

pmpl/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

pmpl/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
      new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

pmpl/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :vehicle_historics, :dependent => :destroy
  has_many :vehicle_dailies, :dependent => :delete_all
  belongs_to :brand
  belongs_to :carmodel
  belongs_to :place

  validates :license_plate, :place_id, :brand_id, :carmodel_id, :year, :presence => true
end

pmpl/app/models/vehicle_daily.rb
class VehicleDaily < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :vehicle_historic

  validates :vehicle_id, :date, :presence => true
end

pmpl/app/models/vehicle_historic.rb
class VehicleHistoric < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :oil
  has_many :vehicle_dailies
  
  validates :status, :vehicle_id, :oil_id, :presence => true
end

pmpl/app/controllers/oils_controller.rb
class OilsController < ApplicationController
  
  def import  
    if notice.blank?
      @notice = ""
    else  
      @notice = notice
    end

    respond_to do |format|
      format.html
    end
  end
  
  def upload
    #file = DataFile.save(params[:upload][:csv])
    
    @file = params[:upload][:csv].read
    @x = 0
    
    FasterCSV.parse(@file).each do |row|
      if @x == 0
        @row = row
        @validate = validate_file()
        if @validate == false
          break;
        end
      else
        @oil = Oil.new
        @oil.name = row[0]
        @oil.save
      end
      @x = @x + 1
    end
    
    respond_to do |format|
      if @validate == false
        format.html { redirect_to(oils_import_path, :notice => 'Encontramos erro(s) na planilha, utilize como modelo a planilha encontrada nessa pagina.') }
      else
        format.html { redirect_to(oils_path, :notice => 'Carmodel was successfully created.') }
      end
    end 
  end
  
  # GET /oils
  # GET /oils.xml
  def index
    @oils = Oil.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @oils }
    end
  end

  # GET /oils/1
  # GET /oils/1.xml
  def show
    @oil = Oil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @oil }
    end
  end

  # GET /oils/new
  # GET /oils/new.xml
  def new
    @oil = Oil.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @oil }
    end
  end

  # GET /oils/1/edit
  def edit
    @oil = Oil.find(params[:id])
  end

  # POST /oils
  # POST /oils.xml
  def create
    @oil = Oil.new(params[:oil])

    respond_to do |format|
      if @oil.save
        format.html { redirect_to(@oil, :notice => 'Oil was successfully created.') }
        format.xml  { render :xml => @oil, :status => :created, :location => @oil }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @oil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /oils/1
  # PUT /oils/1.xml
  def update
    @oil = Oil.find(params[:id])

    respond_to do |format|
      if @oil.update_attributes(params[:oil])
        format.html { redirect_to(@oil, :notice => 'Oil was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @oil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /oils/1
  # DELETE /oils/1.xml
  def destroy
    @oil = Oil.find(params[:id])
    @oil.destroy

    respond_to do |format|
      format.html { redirect_to(oils_url) }
      format.xml  { head :ok }
    end
  end
  
  private
    def validate_file
      if @row[0] != "Nome"
        return false
      end
    end
    
end

pmpl/app/helpers/application_helper.rb
module ApplicationHelper
end

pmpl/app/helpers/brands_helper.rb
module BrandsHelper
end

pmpl/app/helpers/carmodels_helper.rb
module CarmodelsHelper
end

pmpl/app/helpers/oils_helper.rb
module OilsHelper
end

pmpl/app/helpers/places_helper.rb
module PlacesHelper
end

pmpl/app/helpers/users_helper.rb
module UsersHelper
end

pmpl/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

pmpl/app/views/csv/_import.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2><%= page %></h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
	
	  <div class="message errormsg" style="display:<%= (@notice == '' ?'none':'block') %>" ><p><%= @notice %></p></div>
		
	  <%= form_for :upload, :html => { :multipart => true } do |f| -%>
      <p>
        Planilha modelo: <%= link_to "Modelo", Rails.root.join('public', "planilhas", "brand.csv").to_s %> 
      </p>
      <p>
        <%= f.file_field :csv %>
      </p>
      <p>
        <%= f.submit "Importar", :class => "submit small" %>
      </p>
    <% end -%>
		
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
		
</div>		<!-- .block ends -->

pmpl/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Oil Control</title>

  <%= stylesheet_link_tag "style", "jquery.wysiwyg", "facebox", "visualize", "date_input" %>

  <%= javascript_include_tag "jquery", "rails" %>

  	<!--[if lt IE 8]><%= stylesheet_link_tag "ie", :media => "all" %><![endif]-->
</head>
<body>
	
	<div id="hld">
	
		<div class="wrapper">		<!-- wrapper begins -->
			<%
			if current_user
			%>
				<div id="header">
					<div class="hdrl"></div>
					<div class="hdrr"></div>
				
					<h1><a href="#">PMPL</a></h1>
				
					<ul id="nav">
						<li><a href="<%=vehicles_url%>">Veiculo</a></li>
						<li><a href="<%=vehicle_historics_url%>">Caminhão</a></li>
						<li><a href="<%=machine_historics_url%>">Maquina</a></li>
						<li><a href="<%=vehicle_dailies_url%>">Andamento Diario</a></li>
						<li><a href="<%=oils_url%>">Oleo</a></li>
						<li><a href="<%=brands_url%>">Marca</a></li>
						<li><a href="<%=carmodels_url%>">Modelo</a></li>
						<li><a href="<%=places_url%>">Local</a></li>
						<li><a href="<%=new_report_vehicle_historic_url%>">Relatorio</a></li>
					</ul>
					<p class="user">Ola, 
						<%
						if current_user
						%>
							<%=current_user.name%> | <%= link_to "Sair", logout_path %></p>
						<%
						end
						%>
					
				</div>		<!-- #header ends -->		
			<%
	    	end
			%>
			
			<%= yield %>
				
			<div id="footer">
			
				<p class="left"><a href="#">Plano de Manutenção Preventiva de Lubrificação</a></p>
				<p class="right">powered by <%= link_to "Dooit", "http://www.dooit.com.br" %></p>
				
			</div>
		
		</div>						<!-- wrapper ends -->
		
	</div>		<!-- #hld ends -->
	
	<!--[if IE]><%= javascript_include_tag "excanvas" %><![endif]-->
	
	<%= javascript_include_tag "application", "jquery.img.preload", "jquery.filestyle.mini", "jquery.wysiwyg", "jquery.date_input.pack", "facebox", "jquery.visualize", "jquery.visualize.tooltip", "jquery.select_skin", "jquery.tablesorter.min", "ajaxupload", "jquery.pngfix", "custom" %>
	
</body>
</html>