pmpl/config/routes.rb
Oilcontrol::Application.routes.draw do
  
  resources :machine_historics

  get 'brands/import' => 'brands#import'
  post 'brands/import' => 'brands#upload'
  
  get 'carmodels/import' => 'carmodels#import'
  post 'carmodels/import' => 'carmodels#upload'
  
  get 'oils/import' => 'oils#import'
  post 'oils/import' => 'oils#upload'
  
  get 'places/import' => 'places#import'
  post 'places/import' => 'places#upload'
  
  get 'vehicles/import' => 'vehicles#import'
  post 'vehicles/import' => 'vehicles#upload'
  
  resources :report_vehicle_historics

  resources :places

  resources :carmodels

  resources :brands

  resources :vehicle_dailies

  get "user_sessions/new"

  resources :oils

  resources :vehicle_historics

  resources :vehicles
  
  resources :users
  
  resources :user_sessions
  
  match 'vehicle_historics/exchange/:id' => 'vehicle_historics#exchange', :as => :vehicle_historic_exchange
  match 'machine_historics/exchange/:id' => 'machine_historics#exchange', :as => :machine_historic_exchange
  
  match 'vehicles/update_carmodels_select/:id' => 'vehicles#update_carmodels_select'
  
  match 'vehicle_historics/update_oil_select/:id' => 'vehicle_historics#update_oil_select'
  match 'machine_historics/update_oil_select/:id' => 'machine_historics#update_oil_select'

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "vehicles#index"

end

pmpl/app/models/vehicle_historic.rb
class VehicleHistoric < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :oil
  has_many :vehicle_dailies
  
  validates :status, :vehicle_id, :oil_id, :presence => true
end

pmpl/app/controllers/vehicle_historics_controller.rb
class VehicleHistoricsController < ApplicationController
  before_filter [:load_vehicles], :only=>[:new, :edit, :create, :update]
  before_filter [:load_oils], :only=>[:new, :edit]
  
  # GET /vehicle_historics
  # GET /vehicle_historics.xml
  def index
    
    @vehicle_historics_exchange = VehicleHistoric.select("
    veh.license_plate,
    pla.name as place_name,
    oil.name,
    SUM(day.km) as km_atual,
    cmod_oil.km,
    vehicle_historics.id,
    vehicle_historics.date,
    vehicle_historics.km_initial
    ").joins("
    INNER JOIN
    	vehicles veh ON veh.id = vehicle_historics.vehicle_id
    INNER JOIN
      places pla ON pla.id = veh.place_id
    INNER JOIN
        carmodels cmod ON cmod.id = veh.carmodel_id
    INNER JOIN
        oils oil ON oil.id = vehicle_historics.oil_id
    INNER JOIN
        carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    LEFT JOIN
        vehicle_dailies day ON day.vehicle_id = veh.id
    ").where("
      vehicle_historics.status = 'aberto'
    ").group("
    vehicle_historics.id, vehicle_historics.oil_id
    ").having("
      vehicle_historics.km_initial + (km_atual - vehicle_historics.km_initial) >= vehicle_historics.km_initial + cmod_oil.km
    ")
    
    @vehicle_historics_warning = VehicleHistoric.select("
    veh.license_plate,
    pla.name as place_name,
    oil.name,
    SUM(day.km) as km_atual,
    cmod_oil.km,
    vehicle_historics.id,
    vehicle_historics.date,
    vehicle_historics.km_initial,
    cmod_oil.km_warning
    ").joins("
    INNER JOIN
    	vehicles veh ON veh.id = vehicle_historics.vehicle_id
    INNER JOIN
      places pla ON pla.id = veh.place_id
    INNER JOIN
        carmodels cmod ON cmod.id = veh.carmodel_id
    INNER JOIN
        oils oil ON oil.id = vehicle_historics.oil_id
    INNER JOIN
        carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    LEFT JOIN
        vehicle_dailies day ON day.vehicle_id = veh.id
    ").where("
      vehicle_historics.status = 'aberto'
    ").group("
    vehicle_historics.id, vehicle_historics.oil_id
    ").having("
      vehicle_historics.km_initial + (km_atual - vehicle_historics.km_initial) < vehicle_historics.km_initial + cmod_oil.km 
    AND 
      vehicle_historics.km_initial + (km_atual - vehicle_historics.km_initial) + cmod_oil.km_warning >= vehicle_historics.km_initial + cmod_oil.km
    ")
    
    @vehicle_historics_daily = VehicleHistoric.select("
    veh.license_plate,
    pla.name as place_name,
    oil.name,
    IF(day.km != '', SUM(day.km), '0') as km_atual,
    cmod_oil.km,
    vehicle_historics.id,
    vehicle_historics.date,
    vehicle_historics.km_initial,
    cmod_oil.km_warning,
    day.id as day_id
    ").joins("
    INNER JOIN
    	vehicles veh ON veh.id = vehicle_historics.vehicle_id
    INNER JOIN
      places pla ON pla.id = veh.place_id
    INNER JOIN
        carmodels cmod ON cmod.id = veh.carmodel_id
    INNER JOIN
        oils oil ON oil.id = vehicle_historics.oil_id
    INNER JOIN
        carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    LEFT JOIN
        vehicle_dailies day ON day.vehicle_id = veh.id
    ").where("
      vehicle_historics.status = 'aberto'
    ").group("
    vehicle_historics.id, vehicle_historics.oil_id
    ").having("
      (vehicle_historics.km_initial + (km_atual - vehicle_historics.km_initial) + cmod_oil.km_warning < vehicle_historics.km_initial + cmod_oil.km)
    OR
      (day_id is null)
    ")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vehicle_historics }
    end
  end
  
  def update_oil_select    

      @oils = Vehicle.select('
        oils.id,
        oils.name
      ').joins("
        INNER JOIN carmodels ON carmodels.id = vehicles.carmodel_id
        INNER JOIN carmodel_oils co ON co.carmodel_id = carmodels.id
        INNER JOIN oils ON oils.id = co.oil_id
        LEFT JOIN vehicle_historics vh ON vh.vehicle_id = vehicles.id AND vh.oil_id = oils.id
      ").find(:all, :conditions => ["vehicles.id = '#{params[:id]}'   AND
          ( 
        	(
        	SELECT
        		vhis.status
        	FROM
        		vehicle_historics vhis
        	WHERE
        		vhis.vehicle_id = vehicles.id 
        	AND 
        		vhis.oil_id = oils.id
        	ORDER BY
        		vhis.status
        	LIMIT
        		0,1
        	) != 'aberto'
          OR
            vh.id is null
          )"], :group => "oils.id")
      render :partial => "oil", :oils => @oils
  end
  
  def exchange
    @vehicle_historic = VehicleHistoric.find(params[:id])
    
    @vehicle_historic.date = Time.zone.now
    @vehicle_historic.status = "fechado"
    
    @vehicle_historic.save
    
    @km_initial = VehicleDaily.select("
    CASE
      WHEN SUM(vehicle_dailies.km) is null THEN '0'
      WHEN SUM(vehicle_dailies.km) is not null THEN SUM(vehicle_dailies.km) 
     END as km_atual,
    vehicle_dailies.id
    ").find(:first, :conditions => ["
      vehicle_dailies.vehicle_id = '#{@vehicle_historic.vehicle_id}'
    "])
    
    @new_vehicle_historic = VehicleHistoric.new
    @new_vehicle_historic.vehicle_id = @vehicle_historic.vehicle_id
    @new_vehicle_historic.oil_id = @vehicle_historic.oil_id
    @new_vehicle_historic.status = "aberto"
    @new_vehicle_historic.km_initial = @km_initial.km_atual
    @new_vehicle_historic.save
    
    redirect_to(vehicle_historics_url)
  end

  # GET /vehicle_historics/1
  # GET /vehicle_historics/1.xml
  def show
    @vehicle_historic = VehicleHistoric.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vehicle_historic }
    end
  end

  # GET /vehicle_historics/new
  # GET /vehicle_historics/new.xml
  def new
    @vehicle_historic = VehicleHistoric.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vehicle_historic }
    end
  end

  # GET /vehicle_historics/1/edit
  def edit
    @vehicle_historic = VehicleHistoric.find(params[:id])
  end

  # POST /vehicle_historics
  # POST /vehicle_historics.xml
  def create
    @vehicle_historic = VehicleHistoric.new(params[:vehicle_historic])
    @vehicle_historic.status = "aberto"
    
    @km_initial = VehicleDaily.select("
    CASE
      WHEN SUM(vehicle_dailies.km) is null THEN '0'
      WHEN SUM(vehicle_dailies.km) is not null THEN SUM(vehicle_dailies.km) 
     END as km_atual,
    vehicle_dailies.id
    ").find(:first, :conditions => ["
      vehicle_dailies.vehicle_id = '#{@vehicle_historic.vehicle_id}'
    "])

    @vehicle_historic.km_initial = @km_initial.km_atual  
    
    respond_to do |format|
      if @vehicle_historic.save
        format.html { redirect_to(@vehicle_historic, :notice => 'Vehicle historic was successfully created.') }
        format.xml  { render :xml => @vehicle_historic, :status => :created, :location => @vehicle_historic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vehicle_historic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vehicle_historics/1
  # PUT /vehicle_historics/1.xml
  def update
    @vehicle_historic = VehicleHistoric.find(params[:id])
    @vehicle_historic.status = "aberto"

    respond_to do |format|
      if @vehicle_historic.update_attributes(params[:vehicle_historic])
        format.html { redirect_to(@vehicle_historic, :notice => 'Vehicle historic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vehicle_historic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_historics/1
  # DELETE /vehicle_historics/1.xml
  def destroy
    @vehicle_historic = VehicleHistoric.find(params[:id])
    @vehicle_historic.destroy

    respond_to do |format|
      format.html { redirect_to(vehicle_historics_url) }
      format.xml  { head :ok }
    end
  end
  
  private
    def load_vehicles
      @vehicles = Vehicle.select('
        vehicles.id,
        vehicles.license_plate
      ').joins("
        INNER JOIN carmodels ON carmodels.id = vehicles.carmodel_id
        INNER JOIN carmodel_oils co ON co.carmodel_id = carmodels.id
        INNER JOIN oils ON oils.id = co.oil_id
        LEFT JOIN vehicle_historics vh ON vh.vehicle_id = vehicles.id AND vh.oil_id = oils.id
      ").find(:all, :conditions => ["
          carmodels.carmodel_type = 'Caminhão'
          AND
        	(
        	  (
          	SELECT
          		vhis.status
          	FROM
          		vehicle_historics vhis
          	WHERE
          		vhis.vehicle_id = vehicles.id 
          	AND 
          		vhis.oil_id = oils.id
          	ORDER BY
          		vhis.status
          	LIMIT
          		0,1
          	) != 'aberto'
            OR
              vh.id is null
          )"], :group => "vehicles.id").collect { |c| [c.license_plate, c.id] }
    end
    
    def load_oils
      @oils = Array.new
    end
end

pmpl/app/helpers/vehicle_historics_helper.rb
module VehicleHistoricsHelper
end

pmpl/app/views/vehicle_historics/_form.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2><%= page %> Histórico Caminhão</h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
		
		<p class="breadcrumb"><a href="<%= vehicle_historics_url %>">Histórico Caminhão</a> &raquo; <strong><%= page %></strong></p>

		<%= form_for(@vehicle_historic)  do |f| %>
		  <% if @vehicle_historic.errors.any? %>
		    <div class="message errormsg">
		      <p>Não foi possível salvar devido aos seguintes erros:</p>
		
		      <% @vehicle_historic.errors.full_messages.each do |msg| %>
		        <p><%= msg %></p>
		      <% end %>
		    </div>
		  <% end %>
		  <%
		  if page == "Alterar"
		  %>
		  <p>
			  <%= f.label :placa %><br />
			  <%= f.label @vehicle_historic.vehicle.license_plate %>
			</p>
			<%
		  else
			%>
		    <p>
  			  <%= f.label :placa %><br />
  			  <%= f.select :vehicle_id, @vehicles, :prompt => "Selecione", :class => "styled" %>
  			</p>
  		<%
		  end
  		%>
  		<%
		  if page == "Alterar"
		  %>
		  <p>
			  <%= f.label :oleo %><br />
			  <%= f.label @vehicle_historic.oil.name %>
			</p>
			<%
		  else
			%>
		    <p>
  			  <%= f.label :oleo %><br />
  			  <%= f.select :oil_id, @oils, :prompt => "Selecione", :class => "styled" %>
  			</p>
  		<%
		  end
  		%>
        <p>
          <%= f.label :observaçao %><br />
          <%= f.text_area :observation %>
        </p>
		  <p>
		    <%= f.submit page, :class => "submit small" %>
		  </p>
		<% end %>
		
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
		
</div>		<!-- .block ends -->

pmpl/app/views/vehicle_historics/_oil.html.erb
<option value="">Selecione</option>
<% if !@oils.blank? %>
  <% @oils.each do |item| %>
    <option value="<%= item.id %>"><%= item.name  %></option>
  <% end %>
<% end %>

pmpl/app/views/vehicle_historics/edit.html.erb
<%= render 'form', :page => "Alterar" %>

pmpl/app/views/vehicle_historics/index.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2>Histórico Caminhão</h2>
		
		<ul>
			<li><a href="<%=new_vehicle_historic_path%>">Novo Histórico</a></li>
		</ul>
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
	
		<form action="" method="post">
		
		<h2>Troca necessaria</h2>
		
			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">
			
				<thead>
					<tr>
					  <th></th>
					  <th>Local</th>
            <th>Placa</th>
            <th>Oleo</th>
            <th>Km Inicial</th>
            <th>Km Atual</th>
            <th>Km Final</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
				</thead>
				
				<tbody>
				<% @vehicle_historics_exchange.each do |vehicle_historic| %>
          <tr>
            <td><%=image_tag("red.png")%></td>
            <td><%= vehicle_historic.place_name %></td>
            <td><%= vehicle_historic.license_plate %></td>
            <td><%= vehicle_historic.name %></td>
            <td><%= vehicle_historic.km_initial %></td>
            <td><%= vehicle_historic.km_atual %></td>
            <td><%= vehicle_historic.km + vehicle_historic.km_initial %></td>
            <td><%= link_to 'Troca efetuada?', vehicle_historic_exchange_path(vehicle_historic) %></td>
            <td><%= link_to 'Visualizar', vehicle_historic %></td>
            <td><%= link_to 'Editar', edit_vehicle_historic_path(vehicle_historic) %></td>
            <td><%= link_to 'Excluir', vehicle_historic, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
          </tr>
        <%
        end
        %>
				</tbody>
			</table>
			
		  <h2>Troca se aproximando</h2>

  			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

  				<thead>
  					<tr>
  					  <th></th>
  					  <th>Local</th>
              <th>Placa</th>
              <th>Oleo</th>
              <th>Km Inicial</th>
              <th>Km Atual</th>
              <th>Km Final</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
  				</thead>

  				<tbody>
  				<% @vehicle_historics_warning.each do |vehicle_historic| %>
            <tr>
              <td><%=image_tag("yellow.png")%></td>
              <td><%= vehicle_historic.place_name %></td>
              <td><%= vehicle_historic.license_plate %></td>
              <td><%= vehicle_historic.name %></td>
              <td><%= vehicle_historic.km_initial %></td>
              <td><%= vehicle_historic.km_atual %></td>
              <td><%= vehicle_historic.km + vehicle_historic.km_initial %></td>
              <td><%= link_to 'Visualizar', vehicle_historic %></td>
              <td><%= link_to 'Editar', edit_vehicle_historic_path(vehicle_historic) %></td>
              <td><%= link_to 'Excluir', vehicle_historic, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
            </tr>
          <%
          end
          %>
  				</tbody>
  			</table>
  			
  		  <h2>Andamento Diario</h2>

    			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

    				<thead>
    					<tr>
    					  <th></th>
    					  <th>Local</th>
                <th>Placa</th>
                <th>Oleo</th>
                <th>Km Inicial</th>
                <th>Km Atual</th>
                <th>Km Final</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
    				</thead>

    				<tbody>
    				<% @vehicle_historics_daily.each do |vehicle_historic| %>
              <tr>
                <td><%=image_tag("green.png")%></td>
                <td><%= vehicle_historic.place_name %></td>
                <td><%= vehicle_historic.license_plate %></td>
                <td><%= vehicle_historic.name %></td>
                <td><%= vehicle_historic.km_initial %></td>
                <td><%= vehicle_historic.km_atual %></td>
                <td><%= vehicle_historic.km + vehicle_historic.km_initial %></td>
                <td><%= link_to 'Visualizar', vehicle_historic %></td>
                <td><%= link_to 'Editar', edit_vehicle_historic_path(vehicle_historic) %></td>
                <td><%= link_to 'Excluir', vehicle_historic, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
              </tr>
            <%
            end
            %>
    				</tbody>
    			</table>
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
</div>		<!-- .block ends -->

pmpl/app/views/vehicle_historics/new.html.erb
<%= render 'form', :page => "Cadastrar" %>

pmpl/app/views/vehicle_historics/show.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2>Visualizar Oleo</h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
		<p>
      <b>Placa:</b>
      <%= @vehicle_historic.vehicle.license_plate %>
    </p>
		<p>
		  <b>Oleos:</b><br>
		  <%=h @vehicle_historic.oil.name %> <br>
	    - Km: <%=h @vehicle_historic.oil.carmodel_oils[0].km %> <br>
	    - Km Aviso: <%=h @vehicle_historic.oil.carmodel_oils[0].km_warning %> <br>
		</p> 
		
		<p>
		  <b>Km Inicial:</b>
		  <%= @vehicle_historic.km_initial %>
		</p>
		
		<p>
		  <b>Km Aviso:</b>
		  <%= @vehicle_historic.km_initial + @vehicle_historic.oil.carmodel_oils[0].km - @vehicle_historic.oil.carmodel_oils[0].km_warning %>
		</p>
		
		<p>
		  <b>Km Final:</b>
		  <%= @vehicle_historic.km_initial + @vehicle_historic.oil.carmodel_oils[0].km %>
		</p>
		
    <p>
      <b>Observaçao:</b>
      <%= @vehicle_historic.observation %>
    </p>
    
    <% unless @vehicle_historic.date.blank? %>
    <p>
      <b>Data:</b>
      <%= I18n.l @vehicle_historic.date %>
    </p>
    <% end %>
    
    <p>
      <b>Status:</b>
      <%= @vehicle_historic.status %>
    </p>
    
	</div>		<!-- .block_content ends -->

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>		<!-- .block ends -->