pmpl/config/routes.rb
Oilcontrol::Application.routes.draw do
  
  resources :machine_historics

  get 'brands/import' => 'brands#import'
  post 'brands/import' => 'brands#upload'
  
  get 'carmodels/import' => 'carmodels#import'
  post 'carmodels/import' => 'carmodels#upload'
  
  get 'oils/import' => 'oils#import'
  post 'oils/import' => 'oils#upload'
  
  get 'places/import' => 'places#import'
  post 'places/import' => 'places#upload'
  
  get 'vehicles/import' => 'vehicles#import'
  post 'vehicles/import' => 'vehicles#upload'
  
  resources :report_vehicle_historics

  resources :places

  resources :carmodels

  resources :brands

  resources :vehicle_dailies

  get "user_sessions/new"

  resources :oils

  resources :vehicle_historics

  resources :vehicles
  
  resources :users
  
  resources :user_sessions
  
  match 'vehicle_historics/exchange/:id' => 'vehicle_historics#exchange', :as => :vehicle_historic_exchange
  match 'machine_historics/exchange/:id' => 'machine_historics#exchange', :as => :machine_historic_exchange
  
  match 'vehicles/update_carmodels_select/:id' => 'vehicles#update_carmodels_select'
  
  match 'vehicle_historics/update_oil_select/:id' => 'vehicle_historics#update_oil_select'
  match 'machine_historics/update_oil_select/:id' => 'machine_historics#update_oil_select'

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "vehicles#index"

end

pmpl/app/models/machine_historic.rb
class MachineHistoric < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :oil
  has_many :vehicle_dailies
  
  validates :status, :vehicle_id, :oil_id, :presence => true
end

pmpl/app/controllers/machine_historics_controller.rb
class MachineHistoricsController < ApplicationController
  before_filter [:load_vehicles], :only=>[:new, :edit, :create, :update]
  before_filter [:load_oils], :only=>[:new, :edit]
  
  # GET /vehicle_historics
  # GET /machine_historics.xml
  def index
    
    @machine_historics_exchange = MachineHistoric.select("
    veh.license_plate,
    pla.name as place_name,
    oil.name,
    SUM(day.km) as km_sum,
    SUM(day.hour) as hour_sum,
    cmod_oil.km,
    cmod_oil.hour,
    machine_historics.id,
    machine_historics.date,
    machine_historics.hour_initial
    ").joins("
    INNER JOIN
    	vehicles veh ON veh.id = machine_historics.vehicle_id
    INNER JOIN
      places pla ON pla.id = veh.place_id
    INNER JOIN
        carmodels cmod ON cmod.id = veh.carmodel_id
    INNER JOIN
        oils oil ON oil.id = machine_historics.oil_id
    INNER JOIN
        carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    LEFT JOIN
        vehicle_dailies day ON day.vehicle_id = veh.id
    ").where("
      machine_historics.status = 'aberto'
    ").group("
    machine_historics.id, machine_historics.oil_id
    ").having("
      (
         	machine_historics.hour_initial + ((km_sum * cmod_oil.hour / cmod_oil.km + hour_sum) - machine_historics.hour_initial) >= machine_historics.hour_initial + cmod_oil.hour
  	  )
  	  OR
      (
  	      cmod_oil.km is null
  	    AND 
         	machine_historics.hour_initial + (hour_sum - machine_historics.hour_initial) >= machine_historics.hour_initial + cmod_oil.hour
  	  )
    ")
    
    @machine_historics_warning = MachineHistoric.select("
    veh.license_plate,
    pla.name as place_name,
    oil.name,
    SUM(day.km) as km_sum,
    SUM(day.hour) as hour_sum,
    cmod_oil.km,
    cmod_oil.hour,
    machine_historics.id,
    machine_historics.date,
    machine_historics.hour_initial,
    cmod_oil.hour_warning
    ").joins("
    INNER JOIN
    	vehicles veh ON veh.id = machine_historics.vehicle_id
    INNER JOIN
      places pla ON pla.id = veh.place_id
    INNER JOIN
        carmodels cmod ON cmod.id = veh.carmodel_id
    INNER JOIN
        oils oil ON oil.id = machine_historics.oil_id
    INNER JOIN
        carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    LEFT JOIN
        vehicle_dailies day ON day.vehicle_id = veh.id
    ").where("
      machine_historics.status = 'aberto'
    ").group("
    machine_historics.id, machine_historics.oil_id
    ").having("
      (
          machine_historics.hour_initial + ((km_sum * cmod_oil.hour / cmod_oil.km + hour_sum) - machine_historics.hour_initial) < machine_historics.hour_initial + cmod_oil.hour 
        AND 
         	machine_historics.hour_initial + ((km_sum * cmod_oil.hour / cmod_oil.km + hour_sum) - machine_historics.hour_initial) + cmod_oil.hour_warning >= machine_historics.hour_initial + cmod_oil.hour
  	  )
  	  OR
      (
  	    cmod_oil.km is null
  	  AND
  	  	machine_historics.hour_initial + (hour_sum - machine_historics.hour_initial) < machine_historics.hour_initial + cmod_oil.hour 
      AND 
      	machine_historics.hour_initial + (hour_sum - machine_historics.hour_initial) + cmod_oil.hour_warning >= machine_historics.hour_initial + cmod_oil.hour
  	  )
    ")
    
    @machine_historics_daily = MachineHistoric.select("
    veh.license_plate,
    pla.name as place_name,
    oil.name,
    IF(day.km != '', SUM(day.km), '0') as km_sum,
    IF(day.hour != '', SUM(day.hour), '0') as hour_sum,
    cmod_oil.km,
    cmod_oil.hour,
    machine_historics.id,
    machine_historics.date,
    machine_historics.hour_initial,
    cmod_oil.hour_warning,
    day.id as day_id
    ").joins("
    INNER JOIN
    	vehicles veh ON veh.id = machine_historics.vehicle_id
    INNER JOIN
      places pla ON pla.id = veh.place_id
    INNER JOIN
        carmodels cmod ON cmod.id = veh.carmodel_id
    INNER JOIN
        oils oil ON oil.id = machine_historics.oil_id
    INNER JOIN
        carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    LEFT JOIN
        vehicle_dailies day ON day.vehicle_id = veh.id
    ").where("
      machine_historics.status = 'aberto'
    ").group("
    machine_historics.id, machine_historics.oil_id
    ").having("
    (
       	machine_historics.hour_initial + ((km_sum * cmod_oil.hour / cmod_oil.km + hour_sum) - machine_historics.hour_initial) + cmod_oil.hour_warning < machine_historics.hour_initial + cmod_oil.hour
	  )
	  OR
    (
	      cmod_oil.km is null
	    AND 
       	machine_historics.hour_initial + (hour_sum - machine_historics.hour_initial) + cmod_oil.hour_warning < machine_historics.hour_initial + cmod_oil.hour
	  )
    OR
      (day_id is null)
    ")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machine_historics }
    end
  end
  
  def update_oil_select    
      @oils = Vehicle.select('
        oils.id,
        oils.name
      ').joins("
        INNER JOIN carmodels ON carmodels.id = vehicles.carmodel_id
        INNER JOIN carmodel_oils co ON co.carmodel_id = carmodels.id
        INNER JOIN oils ON oils.id = co.oil_id
        LEFT JOIN machine_historics mh ON mh.vehicle_id = vehicles.id AND mh.oil_id = oils.id
      ").find(:all, :conditions => ["vehicles.id = '#{params[:id]}'   AND
          ( 
        	(
        	SELECT
        		mhis.status
        	FROM
        		machine_historics mhis
        	WHERE
        		mhis.vehicle_id = vehicles.id 
        	AND 
        		mhis.oil_id = oils.id
        	ORDER BY
        		mhis.status
        	LIMIT
        		0,1
        	) != 'aberto'
          OR
            mh.id is null
          )"], :group => "oils.id")
      render :partial => "oil", :oils => @oils
  end
  
  def exchange
    @machine_historic = MachineHistoric.find(params[:id])
    
    @machine_historic.date = Time.zone.now
    @machine_historic.status = "fechado"
    
    @machine_historic.save
    
    @machine_initial = VehicleDaily.select("
    SUM(vehicle_dailies.km) as km_sum,
    ifnull(SUM(vehicle_dailies.hour), 0) as hour_sum,
    cmod_oil.km,
    cmod_oil.hour
    ").joins("
    INNER JOIN
     vehicles veh ON veh.id = vehicle_dailies.vehicle_id
    INNER JOIN
     carmodels cmod ON cmod.id = veh.carmodel_id 
    INNER JOIN
     machine_historics mhis ON mhis.vehicle_id = veh.id 
    INNER JOIN
     oils oil ON oil.id = mhis.oil_id
    INNER JOIN
     carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    ").where("
      vehicle_dailies.vehicle_id = '#{@machine_historic.vehicle_id}'
    ").group("
      mhis.id, mhis.oil_id
    ").find(:first)
    
    @new_machine_historic = MachineHistoric.new
    @new_machine_historic.vehicle_id = @machine_historic.vehicle_id
    @new_machine_historic.oil_id = @machine_historic.oil_id
    @new_machine_historic.status = "aberto"
    
    if @machine_initial.km.blank?
        @new_machine_historic.hour_initial = @machine_initial.hour_sum
    else
        @machine_item = CarmodelOil.find(:first, :conditions => ["carmodel_id = '#{@machine_historic.vehicle.carmodel_id}'  AND oil_id = '#{@machine_historic.oil_id}'"])
        
        logger.debug "vale = #{@machine_initial.km_sum}"
        logger.debug "vale = #{@machine_initial.hour_sum}"
        logger.debug "vale = #{@machine_initial.km}"
        logger.debug "vale = #{@machine_initial.hour}"
        
        @new_machine_historic.hour_initial = @machine_initial.km_sum.to_f * @machine_item.hour.to_f / @machine_item.km.to_f + @machine_initial.hour_sum.to_f
    end
    
    @new_machine_historic.save
    
    redirect_to(machine_historics_url)
  end

  # GET /vehicle_historics/1
  # GET /vehicle_historics/1.xml
  def show
    @machine_historic = MachineHistoric.find(params[:id])
    
    @machine_oil = CarmodelOil.find(:first, :conditions => ["oil_id = ? AND carmodel_id = ?", @machine_historic.oil_id, @machine_historic.vehicle.carmodel_id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @machine_historic }
    end
  end

  # GET /vehicle_historics/new
  # GET /vehicle_historics/new.xml
  def new
    @machine_historic = MachineHistoric.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @machine_historic }
    end
  end

  # GET /vehicle_historics/1/edit
  def edit
    @machine_historic = MachineHistoric.find(params[:id])
  end

  # POST /vehicle_historics
  # POST /machine_historics.xml
  def create
    @machine_historic = MachineHistoric.new(params[:machine_historic])
    @machine_historic.status = "aberto"
    
    @machine_initial = VehicleDaily.select("
    SUM(vehicle_dailies.km) as km_sum,
    ifnull(SUM(vehicle_dailies.hour), 0) as hour_sum,
    cmod_oil.km,
    cmod_oil.hour
    ").joins("
    INNER JOIN
     vehicles veh ON veh.id = vehicle_dailies.vehicle_id
    INNER JOIN
     carmodels cmod ON cmod.id = veh.carmodel_id 
    INNER JOIN
     machine_historics mhis ON mhis.vehicle_id = veh.id 
    INNER JOIN
     oils oil ON oil.id = mhis.oil_id
    INNER JOIN
     carmodel_oils cmod_oil ON cmod_oil.carmodel_id = cmod.id AND cmod_oil.oil_id = oil.id
    ").where("
      vehicle_dailies.vehicle_id = '#{@machine_historic.vehicle_id}'
    ").group("
      mhis.id, mhis.oil_id
    ").find(:first)
    
    if @machine_initial.blank?
      @machine_historic.hour_initial = "0"
    elsif @machine_initial.km.blank?
        @machine_historic.hour_initial = @machine_initial.hour_sum
    else
        @machine_item = CarmodelOil.find(:first, :conditions => ["carmodel_id = '#{@machine_historic.vehicle.carmodel_id}'  AND oil_id = '#{@machine_historic.oil_id}'"])
        @machine_historic.hour_initial = @machine_initial.km_sum.to_f * @machine_item.hour.to_f / @machine_item.km.to_f + @machine_initial.hour_sum.to_f
    end
    
    respond_to do |format|
      if @machine_historic.save

pmpl/app/helpers/machine_historics_helper.rb
module MachineHistoricsHelper
end

pmpl/app/views/machine_historics/_form.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2><%= page %> Histórico Maquina</h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
		
		<p class="breadcrumb"><a href="<%= machine_historics_url %>">Histórico Maquina</a> &raquo; <strong><%= page %></strong></p>

		<%= form_for(@machine_historic)  do |f| %>
		  <% if @machine_historic.errors.any? %>
		    <div class="message errormsg">
		      <p>Não foi possível salvar devido aos seguintes erros:</p>
		
		      <% @machine_historic.errors.full_messages.each do |msg| %>
		        <p><%= msg %></p>
		      <% end %>
		    </div>
		  <% end %>
		  <%
		  if page == "Alterar"
		  %>
		  <p>
			  <%= f.label :placa %><br />
			  <%= f.label @machine_historic.vehicle.license_plate %>
			</p>
			<%
		  else
			%>
		    <p>
  			  <%= f.label :placa %><br />
  			  <%= f.select :vehicle_id, @vehicles, :prompt => "Selecione", :class => "styled" %>
  			</p>
  		<%
		  end
  		%>
  		<%
		  if page == "Alterar"
		  %>
		  <p>
			  <%= f.label :oleo %><br />
			  <%= f.label @machine_historic.oil.name %>
			</p>
			<%
		  else
			%>
		    <p>
  			  <%= f.label :oleo %><br />
  			  <%= f.select :oil_id, @oils, :prompt => "Selecione", :class => "styled" %>
  			</p>
  		<%
		  end
  		%>
        <p>
          <%= f.label :observaçao %><br />
          <%= f.text_area :observation %>
        </p>
		  <p>
		    <%= f.submit page, :class => "submit small" %>
		  </p>
		<% end %>
		
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
		
</div>		<!-- .block ends -->

pmpl/app/views/machine_historics/_oil.html.erb
<option value="">Selecione</option>
<% if !@oils.blank? %>
  <% @oils.each do |item| %>
    <option value="<%= item.id %>"><%= item.name  %></option>
  <% end %>
<% end %>

pmpl/app/views/machine_historics/edit.html.erb
<%= render 'form', :page => "Alterar" %>

pmpl/app/views/machine_historics/index.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2>Histórico Maquina</h2>
		
		<ul>
			<li><a href="<%=new_machine_historic_path%>">Novo Histórico</a></li>
		</ul>
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
	
		<form action="" method="post">
		
		<h2>Troca necessaria</h2>
		
			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">
			
				<thead>
					<tr>
					  <th></th>
					  <th>Local</th>
            <th>Placa</th>
            <th>Oleo</th>
            <th>Hora Inicial</th>
            <th>Hora Atual</th>
            <th>Hora Final</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
				</thead>
				
				<tbody>
				<% @machine_historics_exchange.each do |machine_historic| %>
				  <%
				  if machine_historic.km.blank?
				    @hour_atual = machine_historic.hour_sum
				  else
				    @hour_atual = machine_historic.km_sum.to_f * machine_historic.hour.to_f / machine_historic.km.to_f + machine_historic.hour_sum.to_f
				  end
				  %>
          <tr>
            <td><%=image_tag("red.png")%></td>
            <td><%= machine_historic.place_name %></td>
            <td><%= machine_historic.license_plate %></td>
            <td><%= machine_historic.name %></td>
            <td><%= machine_historic.hour_initial %></td>
            <td><%= @hour_atual %></td>
            <td><%= machine_historic.hour + machine_historic.hour_initial %></td>
            <td><%= link_to 'Troca efetuada?', machine_historic_exchange_path(machine_historic) %></td>
            <td><%= link_to 'Visualizar', machine_historic %></td>
            <td><%= link_to 'Editar', edit_machine_historic_path(machine_historic) %></td>
            <td><%= link_to 'Excluir', machine_historic, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
          </tr>
        <% end %>
				</tbody>
			</table>
			
		  <h2>Troca se aproximando</h2>

  			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

  				<thead>
  					<tr>
  					  <th></th>
  					  <th>Local</th>
              <th>Placa</th>
              <th>Oleo</th>
              <th>Hora Inicial</th>
              <th>Hora Atual</th>
              <th>Hora Final</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
  				</thead>

  				<tbody>
  				<% @machine_historics_warning.each do |machine_historic| %>
  				  <%
  				  if machine_historic.km.blank?
  				    @hour_atual = machine_historic.hour_sum
  				  else
  				    @hour_atual = machine_historic.km_sum.to_f * machine_historic.hour.to_f / machine_historic.km.to_f + machine_historic.hour_sum.to_f
  				  end
  				  %>
            <tr>
              <td><%=image_tag("yellow.png")%></td>
              <td><%= machine_historic.place_name %></td>
              <td><%= machine_historic.license_plate %></td>
              <td><%= machine_historic.name %></td>
              <td><%= machine_historic.hour_initial %></td>
              <td><%= @hour_atual %></td>
              <td><%= machine_historic.hour + machine_historic.hour_initial %></td>
              <td><%= link_to 'Visualizar', machine_historic %></td>
              <td><%= link_to 'Editar', edit_machine_historic_path(machine_historic) %></td>
              <td><%= link_to 'Excluir', machine_historic, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
            </tr>
          <% end %>
  				</tbody>
  			</table>
  			
  		  <h2>Andamento Diario</h2>

    			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

    				<thead>
    					<tr>
    					  <th></th>
    					  <th>Local</th>
                <th>Placa</th>
                <th>Oleo</th>
                <th>Hora Inicial</th>
                <th>Hora Atual</th>
                <th>Hora Final</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
    				</thead>

    				<tbody>
    				<% @machine_historics_daily.each do |machine_historic| %>
    				  <%
    				  if machine_historic.km.blank?
    				    @hour_atual = machine_historic.hour_sum
    				  else
    				    @hour_atual = machine_historic.km_sum.to_f * machine_historic.hour.to_f / machine_historic.km.to_f + machine_historic.hour_sum.to_f
    				  end
    				  %>
              <tr>
                <td><%=image_tag("green.png")%></td>
                <td><%= machine_historic.place_name %></td>
                <td><%= machine_historic.license_plate %></td>
                <td><%= machine_historic.name %></td>
                <td><%= machine_historic.hour_initial %></td>
                <td><%= @hour_atual %></td>
                <td><%= machine_historic.hour + machine_historic.hour_initial %></td>
                <td><%= link_to 'Visualizar', machine_historic %></td>
                <td><%= link_to 'Editar', edit_machine_historic_path(machine_historic) %></td>
                <td><%= link_to 'Excluir', machine_historic, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
              </tr>
            <% end %>
    				</tbody>
    			</table>
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
</div>		<!-- .block ends -->

pmpl/app/views/machine_historics/new.html.erb
<%= render 'form', :page => "Cadastrar" %>

pmpl/app/views/machine_historics/show.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2>Visualizar Oleo</h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
		<p>
      <b>Placa:</b>
      <%= @machine_historic.vehicle.license_plate %>
    </p>
		<p>
		  <b>Oleo:</b><br>
		  <%=h @machine_oil.oil.name %> <br>
	    - Km: <%=h @machine_oil.km %> <br>
	    - Hora: <%=h @machine_oil.hour %> <br>
	    - Hora Aviso: <%=h @machine_oil.hour_warning %> <br>
		</p> 
		
		<p>
		  <b>Hora Inicial:</b>
		  <%= @machine_historic.hour_initial %>
		</p>
		
		<p>
		  <b>Hora Aviso:</b>
		  <%= @machine_historic.hour_initial + @machine_oil.hour - @machine_oil.hour_warning %> 
		</p>
		
		<p>
		  <b>Hora Final:</b>
		  <%= @machine_historic.hour_initial + @machine_oil.hour %>
		</p>
		
    <p>
      <b>Observaçao:</b>
      <%= @machine_historic.observation %>
    </p>
    
    <% unless @machine_historic.date.blank? %>
    <p>
      <b>Data:</b>
      <%= I18n.l @machine_historic.date %>
    </p>
    <% end %>
    
    <p>
      <b>Status:</b>
      <%= @machine_historic.status %>
    </p>
    
	</div>		<!-- .block_content ends -->

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>		<!-- .block ends -->