pmpl/config/routes.rb
Oilcontrol::Application.routes.draw do
  
  resources :machine_historics

  get 'brands/import' => 'brands#import'
  post 'brands/import' => 'brands#upload'
  
  get 'carmodels/import' => 'carmodels#import'
  post 'carmodels/import' => 'carmodels#upload'
  
  get 'oils/import' => 'oils#import'
  post 'oils/import' => 'oils#upload'
  
  get 'places/import' => 'places#import'
  post 'places/import' => 'places#upload'
  
  get 'vehicles/import' => 'vehicles#import'
  post 'vehicles/import' => 'vehicles#upload'
  
  resources :report_vehicle_historics

  resources :places

  resources :carmodels

  resources :brands

  resources :vehicle_dailies

  get "user_sessions/new"

  resources :oils

  resources :vehicle_historics

  resources :vehicles
  
  resources :users
  
  resources :user_sessions
  
  match 'vehicle_historics/exchange/:id' => 'vehicle_historics#exchange', :as => :vehicle_historic_exchange
  match 'machine_historics/exchange/:id' => 'machine_historics#exchange', :as => :machine_historic_exchange
  
  match 'vehicles/update_carmodels_select/:id' => 'vehicles#update_carmodels_select'
  
  match 'vehicle_historics/update_oil_select/:id' => 'vehicle_historics#update_oil_select'
  match 'machine_historics/update_oil_select/:id' => 'machine_historics#update_oil_select'

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "vehicles#index"

end

pmpl/app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :vehicles, :dependent => :destroy
  has_many :carmodels, :dependent => :destroy
  
  validates :name, :presence => true
end

pmpl/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def import  
    if notice.blank?
      @notice = ""
    else  
      @notice = notice
    end

    respond_to do |format|
      format.html
    end
  end
  
  def upload
    #file = DataFile.save(params[:upload][:csv])
    
    @file = params[:upload][:csv].read
    @x = 0
    
    FasterCSV.parse(@file).each do |row|
      if @x == 0
        @row = row
        @validate = validate_file()
        if @validate == false
          break;
        end
      else
        @brand = Brand.new
        @brand.name = row[0]
        @brand.save
      end
      @x = @x + 1
    end
    
    respond_to do |format|
      if @validate == false
        format.html { redirect_to(brands_import_path, :notice => 'Encontramos erro(s) na planilha, utilize como modelo a planilha encontrada nessa pagina.') }
      else
        format.html { redirect_to(brands_path, :notice => 'Carmodel was successfully created.') }
      end
    end 
  end
  
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.xml
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.xml
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.xml
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to(@brand, :notice => 'Brand was successfully created.') }
        format.xml  { render :xml => @brand, :status => :created, :location => @brand }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.xml
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to(@brand, :notice => 'Brand was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.xml
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to(brands_url) }
      format.xml  { head :ok }
    end
  end
  
  private
    def validate_file
      if @row[0] != "Nome"
        return false
      end
    end
end

pmpl/app/helpers/brands_helper.rb
module BrandsHelper
end

pmpl/app/views/brands/_form.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2><%= page %> Oleo</h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
		
		<p class="breadcrumb"><a href="<%= oils_url %>">Marca</a> &raquo; <strong><%= page %></strong></p>

		<%= form_for(@brand)  do |f| %>
		  <% if @brand.errors.any? %>
		    <div class="message errormsg">
		      <p>Não foi possível salvar devido aos seguintes erros:</p>
		
		      <% @brand.errors.full_messages.each do |msg| %>
		        <p><%= msg %></p>
		      <% end %>
		    </div>
		  <% end %>
      <p>
        <%= f.label :nome %><br />
        <%= f.text_field :name %>
      </p>
		  <p>
		    <%= f.submit page, :class => "submit small" %>
		  </p>
		<% end %>
		
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
		
</div>		<!-- .block ends -->

pmpl/app/views/brands/edit.html.erb
<%= render 'form', :page => "Alterar" %>

pmpl/app/views/brands/import.html.erb
<%= render "csv/import", :page => "Importar Marca", :file_model => "brand.csv" %>

pmpl/app/views/brands/index.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2>Marca</h2>
		
		<ul>
			<li><a href="<%=new_brand_path%>">Nova Marca</a></li>
			<li><%= link_to "Importar", brands_import_path %></li>
		</ul>
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
	
		<form action="" method="post">
		
			<table cellpadding="0" cellspacing="0" width="100%" class="sortable">
			
				<thead>
					<tr>
					  <th style="width:1px"></th>
            <th>Nome</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
				</thead>
				
				<tbody>
				  <% @brands.each do |brand| %>
            <tr>
              <td style="width:1px"></td>
              <td><%= brand.name %></td>
              <td><%= link_to 'Visualizar', brand %></td>
              <td><%= link_to 'Editar', edit_brand_path(brand) %></td>
              <td><%= link_to 'Excluir', brand, :confirm => 'Tem certeza que deseja excluir?', :method => :delete %></td>
            </tr>
          <% end %>
				</tbody>
				
			</table>
			
		</form>
		
	</div>		<!-- .block_content ends -->
	
	<div class="bendl"></div>
	<div class="bendr"></div>
</div>		<!-- .block ends -->

pmpl/app/views/brands/new.html.erb
<%= render 'form', :page => "Cadastrar" %>

pmpl/app/views/brands/show.html.erb
<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		
		<h2>Visualizar Marca</h2>
		
	</div>		<!-- .block_head ends -->
	
	<div class="block_content">
	
    <p>
      <b>Nome:</b>
      <%= @brand.name %>
    </p>
    
	</div>		<!-- .block_content ends -->

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>		<!-- .block ends -->